/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   expansion.c                                        :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: tmatthew <tmatthew@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2019/04/02 17:03:30 by tmatthew          #+#    #+#             */
/*   Updated: 2019/04/18 19:12:33 by tmatthew         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "../../../includes/shell.h"

/*
** Not all expansions are performed on every word, as explained in the following
** sections.
** The order of word expansion shall be as follows:
** 	Tilde expansion (see Tilde Expansion),
** 	parameter expansion (see Parameter Expansion)
** 	command substitution (see Command Substitution)
** 	arithmetic expansion (see Arithmetic Expansion)
** 	Field splitting (see Field Splitting)
** 		shall be performed on the portions of
** 		the fields generated by the above, unless IFS is null.
** 	Pathname expansion (see Pathname Expansion) shall be performed,
** 		unless set -f is in effect.
** 	Quote removal (see Quote Removal) shall always be performed last.
** The expansions described in this section shall occur in the same shell
** environment as that in which the command is executed.
**
** If the complete expansion appropriate for a word results in an empty field,
** that empty field shall be deleted from the list of fields that form the
** completely expanded command, unless the original word contained single-quote
** or double-quote characters.
**
** The '$' character is used to introduce parameter expansion, command
** substitution, or arithmetic evaluation. If an unquoted '$' is followed by
** a character that is not one of the following:
**
** A numeric character
** The name of one of the special parameters (see Special Parameters)
** A valid first character of a variable name
** A <left-curly-bracket> ( '{' )
** A <left-parenthesis>
** the result is unspecified.
*/

int		full_word_expansion(char ***new, char *old)
{
	int		status;
	char	*parameter;
	char	**fields;

	fields = NULL;
	parameter = old;
	if (OK((status = tilde_expansion(&parameter)))
		&& OK((status = parameter_expansion(&parameter)))
		&& OK((status = command_substitution(&parameter)))
		&& OK((status = arithmetic_expansion(&parameter)))
		&& OK((status = field_splitting(&fields, &parameter)))
		&& OK((status = pathname_expansion(&fields)))
		&& OK((status = quote_removal(&fields))))
		*new = fields;
	return (status);
}

/*
** In each case that a value of word is needed (based on the state of parameter,
** as described below), word shall be subjected to tilde expansion, parameter
** expansion, command substitution, and arithmetic expansion.
*/

int		param_expansion(char **new, char *old)
{
	int		status;
	char	*parameter;

	parameter = old;
	if (OK((status = tilde_expansion(&parameter)))
		&& OK((status = parameter_expansion(&parameter)))
		&& OK((status = command_substitution(&parameter)))
		&& OK((status = arithmetic_expansion(&parameter))))
		*new = parameter;
	return (status);
}

/*
** If the redirection operator is "<<" or "<<-", the word that follows the
** redirection operator shall be subjected to quote removal; it is unspecified
** whether any of the other expansions occur.
*/

int		heredoc_expansion(t_redir *redir, char **new, char *old)
{
	int		status;
	char	*word;

	word = old;
	if (!OK((status = remove_quotes(&old))))
		return (status);
	if (IS_A(word, old))
		redir->heredoc_quoted = FALSE;
	else
		redir->heredoc_quoted = TRUE;
	*new = old;
	return (status);
}

/*
** For the other redirection operators, the word that follows the redirection
** operator shall be subjected to tilde expansion, parameter expansion, command
** substitution, arithmetic expansion, and quote removal. Pathname expansion
** shall not be performed on the word by a non-interactive shell; an interactive
** shell may perform it, but shall do so only when the expansion would result in
** one word.
*/

int		redir_expansion(char **new, char *old)
{
	int		status;
	char	*parameter;
	char	**fields;

	fields = NULL;
	parameter = old;
	if (OK((status = tilde_expansion(&parameter)))
		&& OK((status = parameter_expansion(&parameter)))
		&& OK((status = command_substitution(&parameter)))
		&& OK((status = arithmetic_expansion(&parameter)))
		&& OK((status = expand_pathname(&parameter)))
		&& OK((status = remove_quotes(&parameter))))
		*new = parameter;
	return (status);
}
