/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   signal.c                                           :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: tmatthew <tmatthew@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2018/10/19 19:33:17 by tmatthew          #+#    #+#             */
/*   Updated: 2019/04/23 17:22:52 by tmatthew         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "../../includes/shell.h"

/*
** Intercept SIGTRAP signal generated by debuggers that exits process
*/

void	sigtrap_handler(int sig)
{
	if (sig != SIGTRAP)
		return ;
	ft_printf("SIGTRAP signal caught");
}

/*
** Intercept ctrl-c signals and exit processes
*/

void	child_sig_handler(int sig)
{
	if (sig != SIGCHLD)
		return ;
	g_processes -= 1;
	_exit(1);
}

/*
** Intercept ctrl-c signals and ignore in parent process
*/

void	sig_handler(int sig)
{
	ft_printf("signal caught: %d", sig);
	if (sig != SIGINT)
		return ;
	if (g_processes <= 0)
		write(STDOUT, "\n$>", 3);
}
