/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   signal.c                                           :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: tmatthew <tmatthew@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2018/10/19 19:33:17 by tmatthew          #+#    #+#             */
/*   Updated: 2019/06/13 13:51:21 by tmatthew         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "../../includes/shell.h"

/*
** Intercept SIGTRAP signal generated by debuggers that exits process
*/

void	sigtrap_handler(int sig)
{
	if (sig != SIGTRAP)
		return ;
}

/*
** Intercept ctrl-c signals and ignore in parent process
*/

void	sig_handler(int sig)
{
	(void)sig;
	if (sig != SIGINT)
		return ;
	g_in_process = TRUE;
	return ;
}
